type PemeriksaanApiResponse = {
  id: number,
  bidan_id: number,
  ibu_id: number,
  pelayanan_id: number,
  pendaftaran_id: number,
  harga: number,
  tanggal_kunjungan: string,
  jam_kunjungan: string | null,
  created_at: string,
  updated_at: string,
  pelayanan: {
      id: number,
      jenis_layanan_id: number,
      nama: string,
      harga: number,
      keterangan: string,
      created_at: string,
      updated_at: string,
      deleted_at: string | null
  },
  ibu: {
      id: number,
      user_id: number,
      nik: string,
      golongan_darah: string,
      tempat_lahir: string,
      tanggal_lahir: string,
      pendidikan: number,
      pekerjaan: number,
      alamat_domisili: string,
      telepon: string,
      no_registrasi_kohort_ibu: string | null,
      Nama_Keluarga: string | null,
      berat_badan: number | null,
      tinggi_badan: number | null,
      usia_kehamilan: number | null,
      created_at: string,
      updated_at: string,
      user: {
          id: number,
          username: string | null,
          nama_lengkap: string,
          email: string,
          email_verified_at: string | null,
          role: string,
          created_at: string,
          updated_at: string
      }
  },
  pendaftaran: {
      id: number,
      ibu_id: number,
      bidan_id: number | null,
      bayi_id: number | null,
      pelayanan_id: number,
      tanggal_pendaftaran: string,
      jam_pendaftaran: string | null,
      jam_ditentukan: string | null,
      isVerif: number,
      status: string,
      keluhan: string,
      created_at: string,
      updated_at: string,
      bayi: null | {
        id: number,
        ibu_id: number,
        nama_lengkap: string,
        jenis_kelamin: string,
        nik: string,
        golongan_darah: string,
        tempat_lahir: string,
        tanggal_lahir: string,
        no_akta_kelahiran: string,
        no_registrasi_kohort_bayi: string,
        created_at: string,
        updated_at: string
    },
  },
}
