const MAIN_COLOR = '#FF90BB';
const ALTERNATIVE_PINK_COLOR = '#FFC1DA';
const SECONDARY_COLOR = '#A778B7';
const THIRD_COLOR = '#BD8DBD';
const BUTTON_COLOR = '#6A7AFA';
const BUTTON_COLOR_2 = '#702A5E';
const BUTTON_COLOR_3 = '#F792CC';
const BUTTON_COLOR_4 = '#FFE3ED';
const TEXT_HEADER_COLOR = '#FF75B6';
const TEXT_HEADER_COLOR_2 = '#7B61FF';

const BORDER_COLOR = '#00000015';

export {
  MAIN_COLOR,
  BUTTON_COLOR,
  SECONDARY_COLOR,
  BUTTON_COLOR_2,
  TEXT_HEADER_COLOR,
  TEXT_HEADER_COLOR_2,
  THIRD_COLOR,
  ALTERNATIVE_PINK_COLOR,
  BUTTON_COLOR_3,
  BUTTON_COLOR_4,
  BORDER_COLOR,
};
