const MAIN_COLOR = "#F7AEB7"
const BUTTON_COLOR = "#6A7AFA"
const BUTTON_COLOR_2 = "#702A5E"
const SECONDARY_COLOR = "#A778B7"
const TEXT_HEADER_COLOR = '#FF75B6'
const TEXT_HEADER_COLOR_2 = '#7B61FF'

export {
  MAIN_COLOR,
  BUTTON_COLOR,
  SECONDARY_COLOR,
  BUTTON_COLOR_2,
  TEXT_HEADER_COLOR,
  TEXT_HEADER_COLOR_2,
};
