const MAIN_COLOR = "#FF90BB"
const ALTERNATIVE_PINK_COLOR = "#FFC1DA"
const SECONDARY_COLOR = "#A778B7"
const THIRD_COLOR = "#BD8DBD"
const BUTTON_COLOR = "#6A7AFA"
const BUTTON_COLOR_2 = "#702A5E"
const TEXT_HEADER_COLOR = '#FF75B6'
const TEXT_HEADER_COLOR_2 = '#7B61FF'

export {
  MAIN_COLOR,
  BUTTON_COLOR,
  SECONDARY_COLOR,
  BUTTON_COLOR_2,
  TEXT_HEADER_COLOR,
  TEXT_HEADER_COLOR_2,
  THIRD_COLOR,
  ALTERNATIVE_PINK_COLOR,
};
