export type apiResponse = {
  'id': number,
  'ibu_id': number,
  'bidan_id': number | null,
  'pelayanan_id': number,
  'tanggal_pendaftaran': string,
  'jam_pendaftaran': null | string,
  'status': 'Menunggu Konfirmasi' | 'Disetujui' | 'Dibatalkan' | 'Selesai' | string,
  'keluhan': string,
  'nama_anak': string,
  'umur_anak': number,
  'jam_ditentukan': string,
  'isVerif': boolean | 0 | 1,
  'created_at': string,
  'updated_at': string,
  'pelayanan': {
      'id': number,
      'jenis_layanan_id': number,
      'nama': string,
      'harga': number,
      'kuantitas': number,
      'form_id': number,
      'keterangan': string,
      'created_at': number,
      'updated_at': number,
      'deleted_at': null
  },
  'bayi': {
    'id': number,
    'ibu_id': number,
    'nama_lengkap': string,
    'jenis_kelamin': string,
    'nik': string,
    'golongan_darah': string,
    'tempat_lahir': string,
    'tanggal_lahir': string,
    'no_akta_kelahiran': string,
    'no_registrasi_kohort_bayi': string,
    'no_registrasi_kohort_balita': string,
    'no_catatan_medik_rs': string,
    'anak_ke': number,
}
}